name: TFW
version: '${project.version}'
main: com.tfw.main.TFW
authors: [ AbdulazizCr ]
description: Team Fight Plugin

commands:
  TFW:
    description: General Command
    permission: ""
    aliases:
      - teamfightwar
      - tfws
      - teamvsteam
      - tvst