worldSettings:
  HEART_TEAM: BED_BLOCK
  WorldBorder:
    enable: false
    center: [0.0, 0.0] # [X, Z]
    size: 300
  Breakable_blocks: #https for materials
    - WOOL
    - FIRE
    - WEB
  Placeable_blocks:
    - WOOL
    - FIRE
    - WEB