worldSettings:
  HEART_TEAM: BED_BLOCK
  WorldBorder:
    enable: true
    center:
      - 110
      - 180
    size: 300
  Breakable_blocks:
    - WOOL
    - FIRE
    - WEB
  Placeable_blocks:
    - WOOL
    - FIRE
    - WEB