worldSettings:
  HEART_TEAM: BED
  Weather: "CLEAR"
  Time:
    type: "FIXED" # FIXED,AUTO
    fixed_to_be: DAY
  WorldBorder:
    enable: false
    center: [0.0, 0.0] # [X, Z]
    size: 300
  Breakable_blocks: #https for materials
    - WOOL
    - FIRE
    - WEB
  Placeable_blocks:
    - WOOL
    - FIRE
    - WEB